#Answer: 4613732

'''
@author: Philippe Chretien

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Find the sum of all the even-valued terms in the sequence which do not exceed four million.
'''

if __name__ == '__main__':
    sum = 2
    a, b = 1, 2
            
    while True: 
        current = a + b
        if current >= 4000000:
            break
        
        if current%2 == 0:
            sum += current
            print current, ' -> ', sum
            
        a = b
        b = current