#Answer: 

'''
@author: Philippe Chretien

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

'''

import math

def checkForRoot(candidate):
	roots = 0
	for i in range(1,candidate):
		if candidate%i == 0:
			other = candidate/i
			
			if other == i:
				return roots*2 + 1
			
			if other < i:
				return roots*2
			
			roots += 1
						
	
increment = 1
candidate = 0

while True:
	candidate += increment
	increment += 1
		
	if candidate < 250000:
		continue
		
	if candidate%2 > 0:
		continue
			
	# Test candidate
	roots = checkForRoot(candidate)
	
	if roots > 100:
		print str(candidate) + " -> " + str(roots)
	
	if roots > 500:
		break
				
print "Answer: " + str(candidate)